name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get packages
        run: flutter pub get

      - name: Run analysis
        run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --debug

      - name: Build IPA
        run: flutter build ios --debug --export-method=archive --export-options=method=development

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flutter APK
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flutter IPA
          path: build/ios/ipa/Runner.ipa
