name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

  ios-build:
    runs-on: macos-latest
    needs: android-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Get dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Build iOS
        run: flutter build ipa --release --export-method app-store
